### ISSUE TITLE
Paŭzo en gitara akompano

### ISSUE THREAD

**Issue by firedemon** [fzesch/kantaro#1]
Eta problemo: En la komenco de kantoj, kiam la takto estas malplena, mi ŝatus neniun akompanon kaj neniun simbolon super la notoj. 
1) En certaj kantoj mi analogie al la notoj enmetis ´r´, sed tio rezultas en la skribaĵo ´N. C.´ (verŝajne ´No Chord´).
2) En aliaj kantoj mi skribis nedefinitaĵon kun definita longeco (ekzemple ´gmx4´). Tio jes funkcias, sed ankaŭ rezultas kompreneble en eraro, kiu difektas aliajn aferojn, ekzemple se ni poste volas aŭtomate plukonverti al LaTeX ...

**Comment by fzesch** [comment]
Tu problemo ekzemple okazas en la kanto rano en lageto. Se oni forprenas la x el la rx4, tiam observeblas tio.

**Comment by fzesch** [comment]
Uzu 's' anstataŭ `r`
